"""Zeroing the instrument — the owner's T4 ruling, implemented.

The zero test measured that the anomaly-shuffle null carries a +0.016
calibration bias for skill statistics (a permutation strengthens the
climatology baseline slightly; NIGHT_LOG_2.md has the full diagnosis). The
ruling: measure the zero point directly and subtract it, the way any bench
instrument is zeroed against a known blank.

    zero_offset  = mean skill of K structureless universes (K >= 30),
                   each generated with its own blake2b seed set and run
                   through the IDENTICAL evaluation pipeline
    resolution   = width of that zero distribution's central 95%
    calibrated   = raw_skill - zero_offset

Verdict rule with calibration: REAL requires clearing the null band AND
|calibrated| > resolution. A structureless series now reads ~0 within
resolution — the new pass condition for the zero test.

Analytic cross-check (logged every run, never tuned to match): persistence
on i.i.d. Gaussian anomalies has an analytic no-skill level of 1 - sqrt(2)
~= -0.4142 when the climatology is known exactly. The measured zero_offset
sits above that because a fold-estimated climatology carries sampling error
that inflates the baseline MAE (the denominator). The gap between measured
and analytic must be explainable by that effect alone; if it is not, the
calibration is wrong and saying so beats shipping it.
"""

from __future__ import annotations

import json
import math
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from ..config import PROJECT_ROOT
from ..logging_setup import get_logger
from .harness import stable_trial_seed

log = get_logger("calibration")

CALIBRATION_PATH = PROJECT_ROOT / "reports" / "calibration.json"
K_UNIVERSES = 30
SEED_TAG = "calibration-{k}-{city}"
ANALYTIC_PERSISTENCE_ZERO = 1.0 - math.sqrt(2.0)


def calibration_universe(k: int,
                         weather: dict[str, pd.Series] | None = None,
                         ) -> dict[str, pd.Series]:
    """Structureless universe #k: climatology + i.i.d. Gaussian anomalies.

    Sigma-matched to the real weather panel when available, sine-climatology
    fallback otherwise (same shapes as synthetic_noise_universe, but with a
    per-universe seed set so the K draws are independent).
    """
    from ..domains.weather_domain import _doy_climatology

    out: dict[str, pd.Series] = {}
    if weather:
        for city in sorted(weather):
            s = weather[city].dropna()
            v = s.to_numpy(dtype=float)
            doy = s.index.dayofyear.to_numpy()
            clim = _doy_climatology(doy, v)
            sigma = float((v - clim[doy]).std(ddof=1))
            rng = np.random.default_rng(
                stable_trial_seed(SEED_TAG.format(k=k, city=city)))
            out[city] = pd.Series(clim[doy] + rng.normal(0.0, sigma, len(v)),
                                  index=s.index, name="temperature")
        return out

    idx = pd.date_range("1980-01-01", periods=int(365.25 * 46), freq="D")
    doy = idx.dayofyear.to_numpy()
    for ci in range(10):
        city = f"S{ci}"
        clim = 10.0 * np.sin(2 * np.pi * (doy / 365.25) + ci)
        rng = np.random.default_rng(
            stable_trial_seed(SEED_TAG.format(k=k, city=city)))
        out[city] = pd.Series(clim + rng.normal(0.0, 4.0, len(idx)),
                              index=idx, name="temperature")
    return out


def measure_zero(weather: dict[str, pd.Series] | None = None,
                 k_universes: int = K_UNIVERSES) -> dict:
    """The calibration run: K structureless universes through the identical
    pipeline. Returns the artifact dict (also what gets committed)."""
    from ..domains.weather_domain import PREDICTORS, evaluate_panel

    skills: dict[str, list[float]] = {name: [] for name in PREDICTORS}
    for k in range(k_universes):
        pooled = evaluate_panel(calibration_universe(k, weather))["pooled"]
        for name in PREDICTORS:
            skills[name].append(pooled[name])
        if (k + 1) % 10 == 0:
            log.info("calibration universe %d/%d", k + 1, k_universes)

    out = {
        "_comment": "Zero point of the instrument. Generated by "
                    "src/validation/calibration.py; do not hand-edit.",
        "date": str(date.today()),
        "k_universes": k_universes,
        "seed_tag": SEED_TAG,
        "sigma_matched_to_weather": bool(weather),
        "predictors": {},
        "analytic_cross_check": {
            "persistence_iid_gaussian": round(ANALYTIC_PERSISTENCE_ZERO, 6),
            "note": "measured zero sits above the analytic value because "
                    "fold-estimated climatology inflates the baseline MAE; "
                    "see module docstring. Logged, never tuned.",
        },
    }
    for name in PREDICTORS:
        a = np.array(skills[name])
        lo, hi = np.percentile(a, 2.5), np.percentile(a, 97.5)
        out["predictors"][name] = {
            "zero_offset": round(float(a.mean()), 6),
            "resolution": round(float(hi - lo), 6),
            "p2_5": round(float(lo), 6),
            "p97_5": round(float(hi), 6),
            "skills": [round(float(x), 6) for x in a],
        }
    return out


def write_calibration(artifact: dict, path: Path = CALIBRATION_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(artifact, indent=1) + "\n", encoding="utf-8")
    log.info("wrote %s", path)


def load_calibration(path: Path = CALIBRATION_PATH) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))
